config/routes.rb
Rails.application.routes.draw do

  resources :likes
  resources :comments
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :cities
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6 } 
  validates :content, presence: true

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, only: %i[ new show edit update ]
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user_valid_for_posts_actions, only: %i[ edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comments = Comment.where(commentable_type: "Post", commentable_id: params[:id] )
    session[:commentable_type] = "Post"
    session[:commentable_id] = params[:id]
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.hidden_field :user_id, value: if current_user then current_user.id end %>
    <%= f.button :submit, class: "btn btn-primary btn-sm", label: "Ajouter" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center">
  <h1>NEWS</h1>
  <%if current_user then%>
    <p class="ml-4"><%= link_to 'Créer', new_post_path, class: 'btn btn btn-primary btn-ms' %></p>
    <%end%>
</div>


<div class="d-flex justify-content-center flex-wrap">
  <% @posts.each do |post| %>
    <div class="card rounded bg-light mb-3" style="width: 18em;">
      <div class="card-body text-center">
        <h5 class="card-title"><%= post.title %></h5>
        <p class="card-text font-italic">Rédigé par <%= post.user.first_name %> le <%= post.created_at.strftime("%m/%d/%Y") %></p>
        <p><%= post.likes.length %> likes et <%= post.comments.length %> commentaires</p>
        <% if current_user %>
          <%= link_to 'Voir', post, class: 'btn btn btn-outline-info btn-sm' %>
  
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center" style="width:100%">
  <div class="card " style="min-width:60%">
    <h2 class="display-2"><%= @post.title %> 
    <% if current_user == @post.user then %>
    <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-primary btn-sm"%>
    <%= link_to 'Delete', post_path(@post), method: :delete, class:"btn btn-danger btn-sm"%>
    <% end %> <%= if current_user != @post.user then link_to "Like", new_like_path(user: current_user, likeable_type: "Post", likeable_id: @post.id, redirect: request.path), class: "btn btn-success btn-sm" end%></h2> 
    <p class="text-align-right font-italic">Rédigé par <%=@post.user.first_name%> le <%= @post.created_at.strftime("%m/%d/%Y") %></p>
    <p>Nombre de like <%= @post.likes.length %></p>
    <p class="card-body bg-info"><%= @post.content %></p>
  </div>
  
</div>


<div class="d-flex justify-content-start flex-wrap" style="width: 80%">
  <%= render "comments/list", comment: @comments %>
</div>
<div class="d-flex justify-content-end " style="width: 90%">
  <%= render "comments/form", comment: Comment.new %>
</div>