config/routes.rb
Rails.application.routes.draw do

  resources :likes
  resources :comments
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :cities
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THPnews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarClassic" aria-controls="navbarClassic" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">THPnews</a>
      <div class="collapse navbar-collapse" id="navbarClassic">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
           <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">NEWS</a>
          </li>
          <%if current_user%>
            <li class="nav-item">
              <a class="nav-link" href="<%= users_path %>">UTILISATEURS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= cities_path %>">VILLES</a>
            </li>
          <%end%>
        </ul>
        <ul class="navbar-nav mr-5 my-0 my-lg-0">
          <%if current_user%>
            <div class="btn-group">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %></a>
                <div class="dropdown-menu">
                  <%= link_to "Éditer le profil", "#{users_path}/#{current_user.id}", method: :get , class: "dropdown-item"%>
                  <%= link_to "Se déconnecter", "#{sessions_path}/#{session.id}", method: :delete , class: "dropdown-item" %>
                </div>
              </li>
            </div>
          <%else%>
            <div class="btn-group">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Se connecter</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="<%= new_session_path%>">Se connecter</a>
                  <a class="dropdown-item" href="<%= new_user_path%>">Créer un compte</a>
                </div>
              </li>
            </div>
          <%end%>
        </ul>
      </div>
    </nav>
    <% flash.each do |type, msg| %>
        <div class="alert alert-<%=type%>">
          <%= msg %>
        </div>
    <% end %>
  </header>
    
  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>